[versions]
odc = '12.1.0'
spock = '2.3-groovy-3.0'
junit = '5.10.3'

[libraries]
owasp-dependencyCheck-core = { module = 'org.owasp:dependency-check-core', version.ref = 'odc' }
owasp-dependencyCheck-utils = { module = 'org.owasp:dependency-check-utils', version.ref = 'odc' }
openVuln-clients = { module = 'io.github.jeremylong:open-vulnerability-clients', version = '6.1.7' }
slack-webhook = { module = 'net.gpedro.integrations.slack:slack-webhook', version = '1.4.0' }

junit-jupiter-api = { module = 'org.junit.jupiter:junit-jupiter-api', version.ref = 'junit' }
junit-jupiter-params = { module = 'org.junit.jupiter:junit-jupiter-params', version.ref = 'junit' }
junit-jupiter-engine = { module = 'org.junit.jupiter:junit-jupiter-engine', version.ref = 'junit' }

spock-core = { module = 'org.spockframework:spock-core', version.ref = 'spock' }

[bundles]

[plugins]
gradle-plugin-publish = { id = 'com.gradle.plugin-publish', version = '1.3.0' }